on: [push, pull_request]
name: UnitTesting
jobs:
  test:
    strategy:
      matrix:
        python-version: [2.7, 3.6, 3.7, 3.8, pypy2, pypy3]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    env:
      KEY: "${{ secrets.KEY }}"
    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Print Secret
      run: python main.py
